### ISSUE TITLE
Abomination ncwms not playing nice with Geonetwork Link Monitor

### ISSUE THREAD

**Issue by danfruehauf** [aodn/geoserver-build#100]
## How to reproduce

Hit the following URL (similar to what Geonetwork Link Monitor will use):
http://geoserver-systest.aodn.org.au/geoserver/ncwms?service=WMS&request=GetMap&version=1.1.1&format=image/png&bbox=-180,-90,180,90&srs=EPSG:4326&width=1&height=1&STYLES=&layers=acorn_hourly_avg_rot_qc_timeseries_url/sea_water_velocity

## What happens

Returns 500

## What should happen

Returns 200

**Comment by danfruehauf** [comment]
A URL which returns a 200 is:
http://geoserver-systest.aodn.org.au/geoserver/ncwms?service=ncwms&request=GetMap&version=1.1.1&format=image/png&bbox=-180,-90,180,90&srs=EPSG:4326&width=1&height=1&STYLES=&LAYERS=acorn_hourly_avg_rot_qc_timeseries_url/sea_water_velocity

What changed:
 * `layers=...` -> `LAYERS=...` - can be solved easily
 * `service=WMS` -> `service=ncwms` - a bit more tricky to fix

**Comment by danfruehauf** [comment]
@jonescc Can you please link the relevant tickets/PRs that fixed that and then we can close it?

**Comment by jonescc** [comment]
Fixed by https://github.com/aodn/core-geonetwork/pull/53, https://github.com/aodn/aodn-portal/pull/2092 and https://github.com/aodn/geoserver-build/pull/103
