### ISSUE TITLE
Abomination ncwms does not comply with WMS 100%

### ISSUE THREAD

**Issue by danfruehauf** [aodn/geoserver-build#107]
At the moment there are 2 gaps preventing abomination ncwms from complying with WMS:
- You must pass `SERVICE=ncwms` (instead of `SERVICE=wms`)
- `GetCapabilities` is not supported
## GetCapabilities

Generally when using ncwms, the `GetCapabilities` request is rather useless and supplies you with a ~100mb (or more) XML file with all the time slices ncwms has ever indexed. A more useful `GetCapabilities` command will include `DATASET=`, which will return the `GetCapabilities` only for a single data collection. The latter is probably what we should implement. Not sure what to do about the former.

**Comment by pblain** [comment]
Added to the backlog. Closing here
