### ISSUE TITLE
NCWMS wms version

### ISSUE THREAD

**Issue by fxmzb123** [aodn/geoserver-build#108]
Hi All,

The NCMWS service in GeoServer forced to set WMS version to 1.3.0 when it sends a wms request to THREDDS server.  See below code in Ncwms.java.

public static String wmsVersion = "1.3.0";
wmsParameters.put("VERSION", new String[] { wmsVersion });

Our THREDDS server requires WMS version 1.1.1 and this fixed version number doesn't work for us.

Since the ncwms service only acts as a proxy between portal and THREDDS server, is it ok to remove this line to allow the version set by portal to pass through?  The ncwms verion can be set in portal configuration file.

I also noticed that the getCapabilitiesXml method has fixed version 1.3.0 set, I am not sure whether it will be affected after removing the wmsVersion.

Thanks,
Ming

**Comment by danfruehauf** [comment]
For us, we will have to use 1.3.0. But feel free to submit a PR that uses the version used by the client - and proxied as is to thredds.

**Comment by fxmzb123** [comment]
This issue has been fixed in our forked repository.
