### ISSUE TITLE
GeoServer can lock up getting ncwms metadata

### ISSUE THREAD

**Issue by jonescc** [aodn/geoserver-build#109]
Refer [geoserver-123-jstack-2016-01-27.txt](https://github.com/aodn/geoserver-build/files/105844/geoserver-123-jstack-2016-01-27.txt)

The ncwms plugin performs a wfs call to retrieve indexed file information.  As shown in the file above, if all threads are already busy requesting indexed file information then its not possible for geoserver to respond to the wfs requests and geoserver deadlocks.

**Comment by danfruehauf** [comment]
Refer also:
aodn/internal-discussions#185

**Comment by danfruehauf** [comment]
A potential fix is to use the `FeatureCollection` API instead of the HTTP request that's being used now. I believe that should not be difficult to implement.

This can also cause WPS GGD to get jammed, for exactly the same reason.

**Comment by danfruehauf** [comment]
Closed by #112 and #113
