### ISSUE TITLE
Configurable relative path in GoGoDuck WPS service

### ISSUE THREAD

**Issue by fxmzb123** [aodn/geoserver-build#117]
Original text:
```
Is it possible to define a HTTP url prefix such as server name in config file?

If wfs service returns relative urls, this cause errors in GoGoDuck service as no server name is defined in the relative urls.
```

The GoGoDuck URL mangling should be configurable from the `gogoduck.xml` configuration file found in the geoserver data directory. At the moment, it is hardcoded for IMOS' use.

**Comment by danfruehauf** [comment]
Unfortunately this is not configurable but should be.

For the command line interface, see:
https://github.com/aodn/geoserver-build/blob/master/src/extension/wps/src/main/java/au/org/emii/gogoduck/worker/Main.java#L11

For the WPS process, we take it from `applicationContext.xml`:
https://github.com/aodn/geoserver-build/blob/master/src/extension/wps/src/main/resources/applicationContext.xml#L11

This is not good. This should come from the `gogoduck.xml` config file. But it was not implemented yet. We'll be happy to receive code contributions regarding that.

**Comment by fxmzb123** [comment]
Hi @danfruehauf,

Can you set permission for me to push code back? I have a code fix for this.

Thanks,
Ming

**Comment by pblain** [comment]
@fxmzb123 , you should have access now

**Comment by danfruehauf** [comment]
@pblain Perhaps remove Ming's access to that repository, he's not an eMII developer. He should fork the repository and create a pull request. He should not have write access to this repository.

**Comment by pblain** [comment]
Oh yes.  I thought it was a private repo
