### ISSUE TITLE
Duplicated netcdf download in GoGoDuck

### ISSUE THREAD

**Issue by fxmzb123** [aodn/geoserver-build#119]
User Case:

Our datasets are organized by month as per netcdf file per month. There are 4 time slices (6 hours jump) per day in a month, therefore, every time slice points to a netcdf file, if the time slice is in the same month, it all point to the same netcdf file. Send a WFS request for one month data, it returns  124 matched netcdf files (assume 31 days in a month), and all are basically the same netcdf file. 

In GoGoDuck, it treats these 124 netcdf files are different files and will fire 124 requests to THREDDS server to download the file. This is not desired, is it possible to remove the duplicates before downloading the netcdf files?

Thanks,
Ming

**Comment by danfruehauf** [comment]
This is by design.

Fix your WFS layer to not have duplicates.
