### ISSUE TITLE
GoGoDuck WPS expire time

### ISSUE THREAD

**Issue by fxmzb123** [aodn/geoserver-build#120]
Hi @danfruehauf,

After GoGoDuck finishes the job process and you can query the job status and download the result.
However, the job status query fails after certain time as WPS sets the job to be expired.

Do you know whether the expiry time can be set?

Thanks,
Ming

**Comment by fxmzb123** [comment]
This can be set on the Geoserver admin page.

**Comment by julian1** [comment]
Hi Ming,

I only just saw your comment.

In case it's relevant, we added some more support for controlling time limits for wps jobs here,  

https://github.com/geoserver/geoserver/pull/1188

Though unfortunately it never got merged upstream.

**Comment by julian1** [comment]
Hi @fxmzb123 ,

I only just saw your comment.

In case it's relevant, we added some more support for controlling time limits for wps jobs here,  

https://github.com/geoserver/geoserver/pull/1188

Unfortunately it never got merged upstream.
