### ISSUE TITLE
Email notification sent wrong in GoGoDuck

### ISSUE THREAD

**Issue by fxmzb123** [aodn/geoserver-build#129]
In current implementation, notification email has been sent directly after the job is completed.
However, for a complete wps process, it will still take time to copy the results and make the result downloadable by the end users. If the copying process takes very long time, end users will get the success email before the download link is available, which leads to a bad user experience.

To fix this, email needs to be sent in a wps event listener, which only send email after the whole wps process is completed.

Please also refer to this issues reported in the AODN Portal:
https://github.com/aodn/aodn-portal/issues/2137

**Comment by julian1** [comment]
@fxmzb123 

May relate to Geoserver's WPS job scheduler which (when I investigated a year ago) had no notion of job completion in some contexts. 

Issue was raised with the Geoserver-devel mailing list,

> As soon as the InputStream is returned to the WPS executor, the job is marked as complete, even though it may take many hours to process and stream all the data. Additionally, any new WPS jobs are run immediately without respecting queue limits.

http://osgeo-org.1560.x6.nabble.com/Need-advice-on-managing-resources-for-WPS-in-Geoserver-td5208596.html

**Comment by fxmzb123** [comment]
@julian1 

The listener is a proper way to handle this,  It only fires after the processing and streaming data, which I found it in the geoserver source code. I have fixed it and tested, will submit a PR after @pblain give me permission.

**Comment by pblain** [comment]
@fxmzb123 - closing this as you mentioned you fixed it in your fork. But feel free to re-open if that's not the case. I can't remember why you didn't have permission to submit a PR via your fork, but I'll leave it for now since it was so long ago - if it remains a problem we'll sort it out next time you want to submit a PR.
