### ISSUE TITLE
Use separate parameters for GoGoDuck spatial and temporal search criteria

### ISSUE THREAD

**Issue by jonescc** [aodn/geoserver-build#150]
Spatial and temporal search criteria are currently passed to the GoGoDuck process in a single subset parameter.

This makes the it difficult for a user to determine what needs to be passed without referring to additional documentation.

It also requires the process to perform parsing which wouldn't otherwise be necessary.

Would be good to define each parameter separately so that its easier to describe and make use of them.

**Comment by pblain** [comment]
This is an enhancement. Now in the backlog: https://github.com/aodn/backlog/issues/672
