### ISSUE TITLE
WFS GetFeature request as outputFormat text/javascript returns 500 error

### ISSUE THREAD

**Issue by anguss00** [aodn/geoserver-build#151]
Affects AODN contributors.

Steps to reproduce:
As an example, go to http://reeflifesurvey.com/reef-life-survey/survey-data/ with console open. 
Check out the request http://geoserver-rls.imas.utas.edu.au/geoserver/RLS/ows?service=WFS&version=1.1.0&request=GetFeature&typeName=RLS:SiteListQ&outputFormat=text%2Fjavascript&format_options=callback:loadFeatures&srsname=EPSG:3857&_=1470012709613.

Observed output:
500 error, no WFS response returned in that format.

Expected output:
Correct WFS response.

**Comment by pblain** [comment]
@anguss00 - can't reproduce.  Perhaps this was fixed?

**Comment by anguss00** [comment]
Yes, this was fixed @pblain
