### ISSUE TITLE
Improve GoGoDuck parameter handling

### ISSUE THREAD

**Issue by jonescc** [aodn/geoserver-build#198]
From the geoserver-wps logs:

```
02 Nov 00:51:20 INFO [worker.GoGoDuck] - Validating subset TIME,2014-10-10T00:00:00,2014-10-12T00:00:00;LATITUDE,-33.433849,-32.150743;LONGITUDE,114.15197,115.741219
02 Nov 00:51:20 INFO [worker.GoGoDuck] - Matched Time Pattern: 2014-10-10T00:00:00
02 Nov 00:51:20 INFO [worker.GoGoDuck] - Matched Time Pattern: 2014-10-12T00:00:00
02 Nov 00:51:20 INFO [worker.GoGoDuck] - Matched Latitude/Longitude Pattern: 00,2014
02 Nov 00:51:20 INFO [worker.GoGoDuck] - Matched Latitude/Longitude Pattern: -33.433849,-32.150743
02 Nov 00:51:20 INFO [worker.GoGoDuck] - Matched Latitude/Longitude Pattern: 114.15197,115.741219
02 Nov 00:51:20 ERROR [worker.GoGoDuck] - Your aggregation failed! Reason for failure is: 'Invalid latitude/longitude format for subset: TIME,2014-10-10T00:00:00,2014-10-12T00:00:00;LATITUDE,-33.433849,-32.150743;LONGITUDE,114.15197,115.741219'
```

Looks like GoGoduck relies on the time zone (e.g. Z) to be specified on dates to be able to correctly validate latitude/longitude (https://github.com/aodn/geoserver-build/blob/master/src/extension/wps/src/main/java/au/org/emii/gogoduck/worker/GoGoDuck.java#L148).  

Not sure how someone would work this out from the error returned.  Looks like the requestor spent a bit of time changing the number of decimals on the lat/longitude parameters to get their request to work without success.

**Comment by jonescc** [comment]
Maybe https://github.com/aodn/geoserver-build/issues/150 would help

**Comment by pblain** [comment]
@jonescc - is this still relevant for the Java version?

**Comment by jonescc** [comment]
I haven't revisited parameter validation so still relevant.

**Comment by pmbohm** [comment]
Fixed by https://github.com/aodn/geoserver-build/issues/245
