### ISSUE TITLE
time_coverage_end not updated correctly for Acorn Bonney Coast aggregations

### ISSUE THREAD

**Issue by jonescc** [aodn/geoserver-build#217]
This issue relates to the new version of GoGoDuck being tested in portal-sandbox.aodn.org.au:

### To Reproduce

Request a netcdf download for ACORN Bonney Coast real time.

### What happens

time_coverage_end = "${TIME_END}" is added to the aggregated dataset

### What I expect to happen

A time_coverage_end attribute is added set to the end date time range requested in ISO8601 format.  e.g.

time_coverage_end = "2017-03-15T00:00:00Z"

**Comment by lbesnard** [comment]
This is bizarre. The result is correct for SRS

**Comment by jonescc** [comment]
I think the difference is that it is updating an existing attribute for SRS - for the ACORN dataset I looked it  was trying to add it.   Looking at that dataset now I see that time_coverage_duration is used instead.  @ggalibert should we be attempting to update the duration in this case instead of adding a time_coverage_end attribute?

**Comment by ggalibert** [comment]
No, let's get rid of time_coverage_duration if any and add/update a time_coverage_end attribute.

**Comment by ggalibert** [comment]
This bug is now seen in systest as well.

**Comment by pblain** [comment]
Duplicate
