### ISSUE TITLE
JavaDuck and geospatial_lat/lon_min/max attributes

### ISSUE THREAD

**Issue by ggalibert** [aodn/geoserver-build#228]
On 123 portal.

Steps to reproduce:

Add any radar, GSLA or CARS data collection and in step 2 define a temporal extent so that it includes 2 or 3 time steps (faster). No need to subset spatially.

Proceed to step 3 and select download as netcdf.

What should happen:

The following attributes:
-geospatial_lat_min
-geospatial_lat_max
-geospatial_lon_min
-geospatial_lon_max

should be updated to reflect what is actually found in the aggregated file with values of the same "type" as the LATITUDE/LONGITUDE variables (usually Double) or at least should be numeric (IMOS checker requirement).

What does happen:

The following attributes:
-geospatial_lat_min
-geospatial_lat_max
-geospatial_lon_min
-geospatial_lon_max

are being updated with the correct values but using the "type" String. Below is the difference between one of the original file and the aggregated file:

```
< 		:geospatial_lat_min = -33.433849 ;
< 		:geospatial_lat_max = -30.150743 ;
---
> 		:geospatial_lat_min = "-33.433849" ;
> 		:geospatial_lat_max = "-30.150743" ;
```

**Comment by jonescc** [comment]
Refer https://github.com/aodn/aodn-portal/issues/2472.  This requires a change to geoserver config (refer [Configuring NetCDF Agregation Settings](https://github.com/aodn/geoserver-build/blob/master/src/extension/wps/doc/GOGODUCK_README.md#configuring-gridded-netcdf-aggregation-settings) and [Controlling aggregation output](https://github.com/aodn/geoserver-build/blob/master/src/extension/wps/doc/GOGODUCK_README.md#controlling-aggregation-output)).  Thought this was going to be tested in RC and then deployed to prod by PO's now javaduck has been deployed to production.  @pblain @smancini?

**Comment by ggalibert** [comment]
The problem that is striking to me is that the attribute in the resulting aggregated file is of a different type than the same attribute in the original files. 

I don't think this should be left to a config file (source of typo/error) when by default, any attribute in the aggregated file that already exists in the original file should be of the same type as the one in the original file.

**Comment by jonescc** [comment]
Yes we could do that, but we need to configure the type for datasets which don't have that attribute already anyway.

**Comment by ggalibert** [comment]
Agreed.

**Comment by ggalibert** [comment]
@pblain , what am I supposed to do?

**Comment by jonescc** [comment]
@pblain I think this requires a fix to javaduck to default the attribute type to the original attribute type if not specified.   The PO's can specify it in templates until that fix is made.

**Comment by pblain** [comment]
@ggalibert - please fix it in the template first, and then allocate this back to me for the code fix.

**Comment by ggalibert** [comment]
@jonescc - where are the templates? I cannot find them in wps/gogoduck.xml in the geoserver data directory.

@pblain - I don't seem to be allowed to reallocate this issue to you.

**Comment by jonescc** [comment]
Templates need to be added.  Refer https://github.com/aodn/geoserver-config/pull/444 where @lbesnard is doing something similar and I've outlined what needs to be done.  He may already be adding the required default template to fix this.

**Comment by pblain** [comment]
@ggalibert - I added the data team to the repo - hopefully that allows you to assign issues.  Let me know if not.

**Comment by bhasin85** [comment]
Linked to #229
