### ISSUE TITLE
Time validation not flexible enough for oa_reconstruction aggregations

### ISSUE THREAD

**Issue by jonescc** [aodn/geoserver-build#250]
### To reproduce

Submit an aggregation request for oa_reconstruction e.g [request.txt](https://github.com/aodn/geoserver-build/files/1181815/request.txt)

### What happens

Get an error returned - "Invalid time format for subset: TIME,1870-07-17T19:38:33.16600Z,1870-07-17T19:38:33.16600Z;LATITUDE,-31.6855,-31.6855;LONGITUDE,114.8291,114.8291 Valid time format example: TIME,2009-01-01T00:00:00.000Z,2009-12-25T23:04:00.000Z"

### What should happen

The aggregation is performed and the result returned.

**Comment by jonescc** [comment]
Introduced by https://github.com/aodn/geoserver-build/pull/245

We should get rid of the regex for validation its problematic.  We should use joda times iso8601 parsing option instead - if it parses OK then it should be good enough for us.   We should also add unit tests to ensure the different time possibilities we know about are tested at the very least.

**Comment by pblain** [comment]
This looks to have been fixed. Does anyone know if there's a reason this issue hasn't been closed?

**Comment by jonescc** [comment]
Wasn't linked in the associated PR.
