### ISSUE TITLE
ProvenanceWriter Error on SumoLogic

### ISSUE THREAD

**Issue by bhasin85** [aodn/geoserver-build#258]
`[provenance.ProvenanceWriter] - No template provenance_template_gridded.ftl found for provenance document`

https://service.au.sumologic.com/ui/index.html#section/search/6KCwIe9UlIBvnr8DfIfszklIC1ieZAPW6cM39TUGBYJJMFDUvRcKHBOqYyrZ9DloXFpWnJAtQjYHQ0QfCICdZHazVcCIvSpzCgyKUZ8B55QsEnT4oXzfBdIgTKfCJsJQ

**Comment by jonescc** [comment]
Fixed a long time ago by adding the templates to geoserver_config.  No instance of this error in the logs in the Sumo logs anymore.
