### ISSUE TITLE
JavaDuck for datasets with no temporal information

### ISSUE THREAD

**Issue by ggalibert** [aodn/geoserver-build#260]
On RC when downloading a spatial subset of the "Victorian Coastal Digital Elevation Model (VCDEM 2017)" (Deakin uni):

1. JavaDuck adds the following two global attributes by default:
```
                :time_coverage_start = "${TIME_START}" ;
                :time_coverage_end = "${TIME_END}" ;
```
Since this dataset doesn't have a temporal dimension this is not relevant and should not be added. 

2. This gridded dataset includes a DEPTH variable so that the resulting subset of this variable should be inspected in order to update the following global attributes:
```
                :geospatial_vertical_min = -118.f ;
                :geospatial_vertical_max = 753.9601f ;
```

**Comment by ggalibert** [comment]
@pblain, on a side note, still cannot assign anyone nor add labels in this repo.

**Comment by pblain** [comment]
@ggalibert - assigned it to myself and gave you access for next time.

**Comment by anguss00** [comment]
Part 2 is a feature request, adding a backlog item for it @pblain @ggalibert

**Comment by pblain** [comment]
Needs a backlog item for the remaining part. Craig or Angus will do that.
