### ISSUE TITLE
Netcdf generator merge

### ISSUE THREAD

**Issue by jkburges** [aodn/geoserver-build#32]
It seems as though we've got two "working copies" of ncdfgenerator:

* https://github.com/aodn/geoserver/commits/imos-2.7.1.1/src/community/ncdfgenerator
  * deployed to systest and production
* https://github.com/aodn/DELETE_ME.ncdfgenerator
  * deployed to ???
  * merged in to this project
  * won't be available as a WPS service within the geoserver war, built and run from this project, due to some missing files (see https://github.com/aodn/geoserver/commits/imos-2.7.1.1/src/community/ncdfgenerator)
  * includes some bug fixes not included above

We need to merge the two forks above to get a working WPS/netcdfgenerator, including bug fixes, within geoserver.  The portal integration task depends on this.

**Comment by danfruehauf** [comment]
Hopefully it'll fix everything:

https://github.com/aodn/geoserver-build/pull/33



________________________________

**Comment by jkburges** [comment]
I'm happy for this to be closed now :grinning: Well done everyone.
