### ISSUE TITLE
CQL parsing for ISO8601 time (Geoserver 2.8.x)

### ISSUE THREAD

**Issue by danfruehauf** [aodn/geoserver-build#35]
Try the following (Geoserver 2.7.1.1):

```
curl "http://geoserver-123.aodn.org.au/geoserver/ows?typeName=acorn_hourly_avg_rot_qc_timeseries_url&SERVICE=WFS&outputFormat=csv&REQUEST=GetFeature&VERSION=1.0.0&CQL_FILTER=time%3D2014-06-06T00%3A30%3A00Z&PROPERTYNAME=time"
FID,time
acorn_hourly_avg_rot_qc_timeseries_url.fid-5e81ca8e_1506e615083_-194b,2014-06-06T00:30:00
```

In the geoserver log:

```
16 Oct 13:03:18 INFO [geoserver.wfs] - 
Request: getServiceInfo
16 Oct 13:03:18 INFO [geoserver.wfs] - 
Request: getFeature
    service = WFS
    version = 1.0.0
    baseUrl = http://localhost:8080/geoserver/
    query[0]:
        propertyName[0] = time
        filter = [ time = Fri Jun 06 10:30:00 AEST 2014 ]
        typeName[0] = {imos.mod}acorn_hourly_avg_rot_qc_timeseries_url
    outputFormat = csv
    resultType = results
Formats are: {marvl xml=marvl xml}
```

So far so good.

And against a VM (Geoserver 2.8.0):

```
curl "http://po.aodn.org.au/geoserver/ows?typeName=acorn_hourly_avg_rot_qc_timeseries_url&SERVICE=WFS&outputFormat=csv&REQUEST=GetFeature&VERSION=1.0.0&CQL_FILTER=time%3D2014-06-06T00%3A30%3A00Z&PROPERTYNAME=time"
FID,file_url
```

No results. Geoserver log:

```
16 Oct 13:04:12 INFO [geoserver.wfs] - 
Request: getServiceInfo
16 Oct 13:04:13 INFO [geoserver.wfs] - 
Request: getFeature
    service = WFS
    version = 1.0.0
    baseUrl = http://po.aodn.org.au:80/geoserver/
    query[0]:
        propertyName[0] = time
        filter = [ time = Fri Jun 06 10:30:00 AEST 2014 ]
        typeName[0] = {imos.mod}acorn_hourly_avg_rot_qc_timeseries_url
    outputFormat = csv
    resultType = results
Formats are: {marvl xml=marvl xml}
```

Now, it's not that there isn't data, if I ask for a range, I will get things on 06/06/2014 on the po box:

```
$ curl "http://po.aodn.org.au/geoserver/ows?typeName=acorn_hourly_avg_rot_qc_timeseries_url&SERVICE=WFS&outputFormat=csv&REQUEST=GetFeature&VERSION=1.0.0&CQL_FILTER=time%20%3E%3D%202014-06-05T00%3A00%3A00Z%20AND%20time%20%3C%202014-06-07T00%3A00%3A00Z&PROPERTYNAME=time&sortBy=time"
FID,time
acorn_hourly_avg_rot_qc_timeseries_url.fid-7905037_1506d9509ec_-7fa8,2014-06-05T10:30:00
acorn_hourly_avg_rot_qc_timeseries_url.fid-7905037_1506d9509ec_-7fa7,2014-06-05T11:30:00
acorn_hourly_avg_rot_qc_timeseries_url.fid-7905037_1506d9509ec_-7fa6,2014-06-05T12:30:00
acorn_hourly_avg_rot_qc_timeseries_url.fid-7905037_1506d9509ec_-7fa5,2014-06-05T13:30:00
acorn_hourly_avg_rot_qc_timeseries_url.fid-7905037_1506d9509ec_-7fa4,2014-06-05T14:30:00
acorn_hourly_avg_rot_qc_timeseries_url.fid-7905037_1506d9509ec_-7fa3,2014-06-05T15:30:00
acorn_hourly_avg_rot_qc_timeseries_url.fid-7905037_1506d9509ec_-7fa2,2014-06-05T16:30:00
acorn_hourly_avg_rot_qc_timeseries_url.fid-7905037_1506d9509ec_-7fa1,2014-06-05T17:30:00
acorn_hourly_avg_rot_qc_timeseries_url.fid-7905037_1506d9509ec_-7fa0,2014-06-05T18:30:00
acorn_hourly_avg_rot_qc_timeseries_url.fid-7905037_1506d9509ec_-7f9f,2014-06-05T19:30:00
acorn_hourly_avg_rot_qc_timeseries_url.fid-7905037_1506d9509ec_-7f9e,2014-06-05T20:30:00
acorn_hourly_avg_rot_qc_timeseries_url.fid-7905037_1506d9509ec_-7f9d,2014-06-05T21:30:00
acorn_hourly_avg_rot_qc_timeseries_url.fid-7905037_1506d9509ec_-7f9c,2014-06-05T22:30:00
acorn_hourly_avg_rot_qc_timeseries_url.fid-7905037_1506d9509ec_-7f9b,2014-06-05T23:30:00
acorn_hourly_avg_rot_qc_timeseries_url.fid-7905037_1506d9509ec_-7f9a,2014-06-06T00:30:00
acorn_hourly_avg_rot_qc_timeseries_url.fid-7905037_1506d9509ec_-7f99,2014-06-06T01:30:00
acorn_hourly_avg_rot_qc_timeseries_url.fid-7905037_1506d9509ec_-7f98,2014-06-06T02:30:00
```

If I ask the VM (Geoserver 2.8.0) for the same, just without the trailing `Z`, it seems to work:

```
curl "http://po.aodn.org.au/geoserver/ows?typeName=acorn_hourly_avg_rot_qc_timeseries_url&SERVICE=WFS&outputFormat=csv&REQUEST=GetFeature&VERSION=1.0.0&CQL_FILTER=time%3D2014-06-06T00%3A30%3A00&PROPERTYNAME=time"
FID,time
acorn_hourly_avg_rot_qc_timeseries_url.fid-7905037_1506d9509ec_-7f96,2014-06-06T00:30:00
```

I don't quite understand where and what time conversion is being done. However this needs to be dealt with as it will affect both GoGoDuck and the ncwms controller.

**Comment by jkburges** [comment]
The versions of geotools being used are 13.1 and 14.0 for geoserver 2.7.1.1 and 2.8.0 respectively.  Looking at the commit log between those two versions, I found this: https://github.com/geotools/geotools/pull/775/files

Possibly the source of this problem, investigating now...

**Comment by jkburges** [comment]
> Possibly the source of this problem, investigating now...

Disregard this, the commit doesn't seem to make a difference...

**Comment by jkburges** [comment]
I think it's this change: https://github.com/geotools/geotools/pull/858/files#diff-b9e6e947d7221cb94fd57bb37eb1bd0eR153

What I am seeing is as follows:

CQL time | SQL time (geoserver-123) | SQL time (PO box)
-------------|------------|-----------
2014-06-06T00:30:00Z|2014-06-05T14:30:00Z|2014-06-06 10:30:00.0
2014-06-06T00:30:00|2014-06-05T14:30:00Z|2014-06-06 00:30:00.0

As can be seen, the older version of the code, as deployed on geoserver-123, is incorrectly converting the CQL date as if it was *local time*, regardless of the timezone *actually* specified.

**Comment by jkburges** [comment]
Setting the geoserver default timezone (with property `-Duser.timezone=UTC`) results in the following:

CQL time | SQL time (PO box)
-------------|-----------
2014-06-06T00:30:00Z|2014-06-06 00:30:00.0
2014-06-06T00:30:00|2014-06-06 00:30:00.0

and results in a record being returned, as in geoserver-123 currently.

I'm not sure that this is really a fix, I wouldn't mind getting a second opinion on this.

**Comment by danfruehauf** [comment]
It'd be good to understand what's the *correct* behaviour, and if needed, fix the rest of the stuff around it (portal, GGD, etc). Better than breaking everything so it seems to look fixed :)

**Comment by jkburges** [comment]
FYI: the relevant column in the DB is of PostgreSQL type "timestamp without time zone", and according to the [documentation](http://www.postgresql.org/docs/9.3/static/datatype-datetime.html): 

<blockquote>
if no time zone is stated in the input string, then it is assumed to be in the time zone indicated by the system's TimeZone parameter
</blockquote>

which is "Australia/Hobart", in the case of the PO box.

**Comment by danfruehauf** [comment]
I might have to back paddle on that then ;)

Probably then the correct solution is to convert those row to be UTC, across the board. Hard work...

**Comment by jkburges** [comment]
Ref: https://github.com/aodn/chef-private/pull/1633

A workaround, which would also need to be deployed to production and rc, if it works in systest.  We may also get some further info in response to a question to the geotools mailing list.

@kereid do you have any test cases which cover something like the OP here?  e.g. a "Download list of URLs" download, with a specific time filter, and then check that the timestamp in the downloaded list of URLs matches the time filter?

**Comment by pblain** [comment]
@jonescc - is this resolved by your latest fix?  Can this issue be closed?

**Comment by pblain** [comment]
@kereid - could you please add a test case for this (if you don't already have one) https://github.com/aodn/geoserver-build/issues/35#issuecomment-153562252.  Then could you please close the issue?

**Comment by kereid** [comment]
Closing have Added test case
