### ISSUE TITLE
ncdfgenerator tests fail

### ISSUE THREAD

**Issue by danfruehauf** [aodn/geoserver-build#42]
`GenerationIT` tests fail due to not having postgres and other environment variables.

Tests were commented out at:
https://github.com/aodn/geoserver-build/pull/41

The tests in question are at:
https://github.com/aodn/geoserver-build/blob/master/src/extension/ncdfgenerator/src/test/java/au/org/emii/ncdfgenerator/GenerationIT.java

**Comment by jonescc** [comment]
Tests reinstated.  Just requires using  mvn install -DskipITs in an environment where a database hasn't been setup.
