### ISSUE TITLE
WPS netcdfgenerator limits

### ISSUE THREAD

**Issue by jkburges** [aodn/geoserver-build#45]
Currently, the `NetcdfOutputProcess` requires a cql filter to be provided in the request.  Conversely, the portal enforces no such behaviour, meaning that it's possible for a user to request a "Download Later" download which will error.

There are two options:

1. Make the cql filter optional on the backend
1. Enforce that a collection is subsetted in the portal before requesting to "Download Later"

Note: even if no filter is provided, the WPS time execution limit will protect against too large requests.

**Comment by jkburges** [comment]
@pblain thoughts?  I think this needs to be resolved before WPS is released in portal, as it's pretty easy for users to submit something that will fail as it stands currently.

**Comment by danfruehauf** [comment]
Regarding the row limit, let the WPS time execution limit take care of that - and it already does.

**Comment by jkburges** [comment]
Oh ok, I forgot about that.  So, people agree that the best option is (1) from above?

**Comment by danfruehauf** [comment]
I give option (1) a :+1: - more generic.

**Comment by pblain** [comment]
@jkburges, yes option 1 is my preference. Seems simpler and I don't see a downside.
