### ISSUE TITLE
Error using csv-with-metadata-header and workspaces with URL-style namespaces

### ISSUE THREAD

**Issue by markhepburn** [aodn/geoserver-build#73]
(This might be a bit overly-specific, and I haven't tried to reproduce it outside this one case of ours, sorry)

We have a few layers using the default workspace "cite" with namespace URI "http://www.opengeospatial.net/cite".  Downloading these with the csv+metadata plugin causes a NPE:

```
11 Nov 12:05:57 ERROR [geoserver.ows] - 
java.lang.NullPointerException
        at au.org.emii.geoserver.wfs.response.CSVWithMetadataHeaderOutputFormat.getDataStoreForFeatureCollection(CSVWithMetadataHeaderOutputFormat.java:121)
        at au.org.emii.geoserver.wfs.response.CSVWithMetadataHeaderOutputFormat.getMetadataFeatureName(CSVWithMetadataHeaderOutputFormat.java:134)
        at au.org.emii.geoserver.wfs.response.CSVWithMetadataHeaderOutputFormat.write(CSVWithMetadataHeaderOutputFormat.java:79)
```

Ie, [this line](https://github.com/aodn/geoserver-build/blob/d10f982cc9ff1dabc0804b44c51f78d521b54eb6/src/main/src/main/java/au/org/emii/geoserver/wfs/response/CSVWithMetadataHeaderOutputFormat.java#L121).

If I change the namespace to "cite" or "citens" for example, it seems to be fine.  Regular outputFormat=CSV downloads are also fine.

**Comment by danfruehauf** [comment]
I'm trying to get my head around it. Is this happening when the workspace is undefined and the default workspace should be used?

**Comment by markhepburn** [comment]
I don't think so -- the workspace is set.

**Comment by markhepburn** [comment]
So just to add a bit more info...

This request always worked (format, regular CSV): http://geoserver.imas.utas.edu.au/geoserver/cite/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=cite:Seamap_contours_5m_Geo&maxFeatures=10000&outputFormat=CSV

This one was failing (csv with metadata header; note that the workspace *is* specified):               http://geoserver.imas.utas.edu.au/geoserver/cite/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=cite:Seamap_contours_5m_Geo&maxFeatures=10000&outputFormat=csv-with-metadata-header

The workspace was configured with name **cite** and namespace URI **http://www.opengeospatial.org/cite**.

When I changed the *namespace URI* to something like **cite** or **citens**, it worked fine.  I did verify that the error repeated when I changed it *back* to the URL style namespace, but I haven't tried to reproduce it on any fresh examples, sorry.

**Comment by pblain** [comment]
@markhepburn - I'm reviewing old issues. Is this still happening?

**Comment by markhepburn** [comment]
That's taking me back -- but I just tried again, and yes if I change the namespace URI back to a URL format I received an error.  Changed it back to just "cite" and it was fine again.

**Comment by pblain** [comment]
@markhepburn - thanks for that.  We'll look into it - probably next iteration

**Comment by pmbohm** [comment]
I'm not spotting an error here. 

This works:
http://geoserver.imas.utas.edu.au/geoserver/cite/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=cite:Seamap_contours_5m_Geo&maxFeatures=10000&outputFormat=csv-with-metadata-header
As does this:
http://geoserver.imas.utas.edu.au/geoserver/cite/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=Seamap_contours_5m_Geo&maxFeatures=10000&outputFormat=csv-with-metadata-header
And without any namespace info at all:
http://geoserver.imas.utas.edu.au/geoserver/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=Seamap_contours_5m_Geo&maxFeatures=10000&outputFormat=csv-with-metadata-header

**Comment by pmbohm** [comment]
There seems to be a problem with the get capabilities at the moment?

http://geoserver.imas.utas.edu.au/geoserver/ows?service=wms&version=1.1.1&request=GetCapabilities

The last few lines (7619 lines) suggest its not well formed:
```
          <Abstract>A sample style that just prints out a purple square</Abstract>
          <LegendURL width="20" height="20">
            <Format>image/png</Format>
            <OnlineResource xmlns:xlink="http://www.w3.org/1999/xlink" xlink:type="simple" xlink:href="http://geoserver.imas.utas.edu.au/geoserver/wms?request=GetLegendGraphic&amp;format=image%2Fpng&amp;width=20&amp;height=20&amp;layer=imas%3ANH3_CMCrawford_Estuarine_Health_Tasmania_GV"/>
          </LegendURL>
        </Style>
      </%
```

**Comment by markhepburn** [comment]
@pmbohm (I'm pretty sure that's just your browser truncating the response that you're seeing there; try curl?)

Those layers are working because the issue seems to be in the configuration, not in the format of the request itself.  Let me know if you can't reproduce it on your own server.

**Comment by pmbohm** [comment]
The get capabilities request is via curl after seeing the issue via the browser. I'll try a download of that layer from beginning to end via the portal. I'll see an issue then with the current configuration?

**Comment by pmbohm** [comment]
@markhepburn The getCapabilities is broken
```
➜  /tmp  curl 'http://geoserver.imas.utas.edu.au/geoserver/ows?service=wms&version=1.1.1&request=GetCapabilities' -o imas2.xml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  271k    0  271k    0     0   506k      0 --:--:-- --:--:-- --:--:-- 2170k
➜  /tmp  tail imas2.xml
        <Style>
          <Name>point</Name>
          <Title>A boring default style</Title>
          <Abstract>A sample style that just prints out a purple square</Abstract>
          <LegendURL width="20" height="20">
            <Format>image/png</Format>
            <OnlineResource xmlns:xlink="http://www.w3.org/1999/xlink" xlink:type="simple" xlink:href="http://geoserver.imas.utas.edu.au/geoserver/wms?request=GetLegendGraphic&amp;format=image%2Fpng&amp;width=20&amp;height=20&amp;layer=imas%3ANH3_CMCrawford_Estuarine_Health_Tasmania_GV"/>
          </LegendURL>
        </Style>
      </%
➜   /tmp
```

**Comment by pmbohm** [comment]
BTW csv-with-metadata-header downloads are not enabled in our portal configuration for your server

**Comment by markhepburn** [comment]
@pmbohm No you wouldn't see the error with that layer as it stands (we have a workaround, and I don't want to leave it broken); the repro case for us at least is the namespace URI in the workspace configuration, not in the request.

Curious about the GetCapabilities; I'll check the logs for clues later.  It's pretty reliable, I'd suspect either some max-size parameter or an internal error.

**Comment by markhepburn** [comment]
@pmbohm Couldn't repro in your test environment?  (I'm not fussed; it's not our software, and we have a work-around :))

Thanks for the heads-up about GetCap; turned out to be a layer without a default style.  Fixed now.
