### ISSUE TITLE
Layer filter extension does not include required files

### ISSUE THREAD

**Issue by dnahodil** [aodn/geoserver-build#79]
It seems that the jar being built and included in the GeoServer war does not include [LayerPage.html](https://github.com/aodn/geoserver-build/blob/d10b48fef3d95ea773d6ec972875fd4cad205893/src/extension/layer-filters/src/main/java/au/org/emii/geoserver/extensions/filters/LayerPage.html) and [layer_filters.css](https://github.com/aodn/geoserver-build/blob/d10b48fef3d95ea773d6ec972875fd4cad205893/src/extension/layer-filters/src/main/java/au/org/emii/geoserver/extensions/filters/layer_filters.css). These missing files cause a blank page when you click the 'WMS Layer Filters' link and prevent you from editing any filters.

**Comment by danfruehauf** [comment]
@xhoenner Aha, there is already a bug for that.

Screenshot for that:
![geoserverfilters](https://cloud.githubusercontent.com/assets/830676/12227251/94250af6-b87d-11e5-83f9-f466dbd26354.jpg)

**Comment by xhoenner** [comment]
It is also worth mentioning that when I added manually a filters.xml file in the folder of the WFS layer I wanted to publish I couldn't see those filters on my PO's 123 portal.

**Comment by danfruehauf** [comment]
@xhoenner Umn... really? Did you add them in the right place?

**Comment by xhoenner** [comment]
yes I did and double checked again, still get this message 'Filtering of this collection is not available at this time' in Step 2.

**Comment by xhoenner** [comment]
>yes I did and double checked again, still get this message 'Filtering of this collection is not available at this time' in Step 2.

Never mind, the XML was misconfigured. Thanks @danfruehauf
