### ISSUE TITLE
Abomination ncwms parameters need to be configurable

### ISSUE THREAD

**Issue by danfruehauf** [aodn/geoserver-build#82]
I naively thought that having the parameters externalized via spring is going to be good enough to later override them by chef. Little did I know.

The parameters at the following file needs to be externalized and controlled via CM (chef in our case):
https://github.com/aodn/geoserver-build/blob/master/src/extension/ncwms/src/main/resources/applicationContext.xml

The main parameters we need to be able to control are:
 * wfsServer
 * urlSubstitutions

It's possible to also embed them in a geoserver xml (such as ncwms.xml). GoGoDuck does that.

It'll also be important in regards to AODN contributors as they would like to reuse that code, obviously with different end points for infrastructure.

**Comment by jonescc** [comment]
Specifying configuration values in a geoserver xml file is more consistent with how geoserver itself and other plugins are normally configured.  Any reason why you don't want to do this?

**Comment by danfruehauf** [comment]
@jonescc That's probably the desired thing to do. Didn't do it at the time because I didn't focus on that. Thought that externalizing to spring will be good enough - apparently not.

GGD uses XML (gogoduck.xml) to read configuration values, that is, as you said, the more consistent way of doing it...

**Comment by jonescc** [comment]
Have a look at https://github.com/aodn/geoserver-build/compare/externalise-ncwms-config?expand=1 to see how you can externalise using properties.

With these changes its possible to specify the wfsServer and url substitutions file as command line parameters:

    -DwfsServer=https://geoserver-systest.aodn.org.au/geoserver \
    -DurlSubstitutions=file:///var/lib/tomcat_7/default/webaps/geoserver/conf/geoserver/url_substitutions.properties

or an override properties file as a command line parameter

    -Dconfig=/var/lib/tomcat_7/default/webaps/geoserver/conf/geoserver/ncwms_config_overrides.properties

(would still need a separate url substitutions file if overriding those)

xml config would be better though

**Comment by danfruehauf** [comment]
I think lets go with XML config. Because this will also entail shuffling more chef code around. With XML config we have the ability to inject variables easily. Like:
https://github.com/aodn/chef-private/blob/master/nodes/5-nec-mel.emii.org.au.json#L135

**Comment by jonescc** [comment]
Agreed.  Just wanted to sghow that I did look at the properties option ;-)

**Comment by jonescc** [comment]
Fixed by 0e705c185b0eee6af3fb21a2241c7d9acb4c6fb6

**Comment by danfruehauf** [comment]
:+1: Thanks @jonescc
