### ISSUE TITLE
GoGoDuck getting stuck performing subset

### ISSUE THREAD

**Issue by jonescc** [aodn/geoserver-build#90]
# To reproduce problem 

1. Run up latest portal/geoserver wps changes in po box
1. Modify acorn wps example to use subset TIME,2014-06-01T00:30:00.000Z,2014-06-06T02:30:00.000Z;LATITUDE,-90.0,90.0;LONGITUDE,-180.0,180.0
1. use curl to submit subset for processing

# What happens

Job never finishes processing

# What I expect to happen

Job finishes processing a subsetted file is available

**Comment by danfruehauf** [comment]
Reproduced with:
```
mvn exec:java -Dexec.mainClass=au.org.emii.gogoduck.worker.Main -Dexec.args="-l 200 -g http://geoserver-123.aodn.org.au/geoserver -p acorn_hourly_avg_rot_qc_timeseries_url -s TIME,2014-06-01T00:30:00.000Z,2014-06-06T02:30:00.000Z;LATITUDE,-90.0,90.0;LONGITUDE,-180.0,180.0 -o output.nc"
```
