### ISSUE TITLE
GoGoDuck can't handle -90, -180 to 90, 180 subset

### ISSUE THREAD

**Issue by jonescc** [aodn/geoserver-build#91]
# To reproduce problem 

1. Run up latest portal/geoserver wps changes in po box
1. Modify acorn wps example to use subset TIME,2014-06-01T00:30:00.000Z,2014-06-06T02:30:00.000Z;LATITUDE,-90,90;LONGITUDE,-180,180 (which is in the format that the portal creates when no bounding box is specified)
1. use curl to submit subset for processing

# What happens

Job returns an error (not a netcdf file)

# What I expect to happen

Job finishes processing and a subsetted file is available

**Comment by danfruehauf** [comment]
Important to note that if you use:
```
LATITUDE,-90.0,90.0;LONGITUDE,-180.0,180.0
```
Then it works. Needs to format parameters properly for `ncks`.

**Comment by danfruehauf** [comment]
After some discussions, best way to fix it at the moment is to patch portal to send `-90.0,90.0` and `-180.0,180.0`.

Then, submit a bug to nco, stating nco cannot handle subsets that are integers (and do not have a floating point).

Next, eliminate use of `ncks` in GGD.

**Comment by danfruehauf** [comment]
Mitigated by https://github.com/aodn/aodn-portal/pull/2083

**Comment by jonescc** [comment]
Adding decimal to fix this is fine.
